
# This file is automatically generated by setup.py
short_version = '0.2.1'
build_number = '4'
version = '0.2.1.dev4'
full_version = '0.2.1.dev4-01da6f6'
git_revision = '01da6f6581be5ef52814eda308afb484d647462b'
release = False
