
# This file is automatically generated by setup.py
short_version = '0.2.0'
version = '0.2.0.dev1'
full_version = '0.2.0.dev1-f37d568'
git_revision = 'f37d568a9de528e360d2a8a4b18ed4e01e25c7a1'
release = False
