
# This file is automatically generated by setup.py
short_version = '0.2.2'
build_number = '0'
version = '0.2.2.dev0'
full_version = '0.2.2.dev0'
git_revision = 'e02fc8c9d54e5a20fc75a701e600ea43789d77fc'
release = True
